// Stage-one interface localization. Educational question packs remain authored in French.
const uiCopy={
  'nav a:nth-child(1)':['Explorer','Explore'],'nav a:nth-child(2)':['Mémoire','Memory'],'nav a:nth-child(3)':['Provinces','Provinces'],'nav a:nth-child(4)':['Sprint','Sprint'],'nav a:nth-child(5)':['Quiz','Quiz'],'nav a:nth-child(6)':['Classe','Classroom'],
  '.hero .eyebrow':['L’aventure commence ici','The adventure starts here'],'.hero h1':['La RDC comme tu ne l’as <em>jamais explorée.</em>','The DRC as you have <em>never explored it.</em>'],'.hero-copy>p':['Des rives du fleuve Congo aux sommets des Virunga, pars à la découverte d’un pays aux mille histoires.','From the Congo River to the Virunga peaks, discover a country with a thousand stories.'],'.hero-actions .primary':['Commencer l’aventure →','Start the adventure →'],'.hero-actions .secondary':['◎ Explorer les thèmes','◎ Explore topics'],'.scroll-cue':['DÉFILE POUR EXPLORER ↓','SCROLL TO EXPLORE ↓'],
  '.daily-streak small':['SÉRIE ACTUELLE','CURRENT STREAK'],'.daily-label span':['✦ DÉCOUVERTE DU JOUR','✦ DAILY DISCOVERY'],'.week-heading small':['MES 7 DERNIERS JOURS','MY LAST 7 DAYS'],'.week-heading>span':['Objectif : 7 jours','Goal: 7 days'],
  '#explorer .section-heading .eyebrow':['Choisis ta route','Choose your path'],'#explorer h2':['Un pays, mille découvertes','One country, a thousand discoveries'],'#explorer .section-heading>p':['Chaque parcours contient des histoires courtes, des faits étonnants et des défis.','Every journey contains short stories, surprising facts and challenges.'],
  '#memory .eyebrow':['Jeu de mémoire','Memory game'],'#memory h2':['Les trésors<br>du Congo','Treasures<br>of the Congo'],'#memory .memory-copy>p':['Retourne les cartes et associe chaque trésor à sa signification. Trouve les six paires avec le moins de coups possible.','Turn over the cards and match each treasure with its meaning. Find all six pairs in as few moves as possible.'],
  '#provinces .eyebrow':['Carte d’exploration','Exploration map'],'#provinces h2':['26 provinces.<br>26 identités.','26 provinces.<br>26 identities.'],'#provinces .province-copy>p:first-of-type':['Découvre les chefs-lieux, paysages et repères de chaque province.','Discover the capitals, landscapes and landmarks of every province.'],'.map-header span':['CARTE INTERACTIVE','INTERACTIVE MAP'],'.map-header h3':['Voyage à travers la RDC','Journey across the DRC'],'.map-header>small':['CARTE SCHÉMATIQUE · NON DESTINÉE À LA NAVIGATION','SCHEMATIC MAP · NOT FOR NAVIGATION'],'#mapProvince':['Choisis une province','Choose a province'],'#mapDescription':['Sélectionne un point sur la carte pour découvrir son chef-lieu et un repère important.','Select a point on the map to discover its capital and an important landmark.'],'#openMapProfile':['Ouvrir le profil →','Open profile →'],
  '#sprint .eyebrow':['Nouveau jeu','New game'],'#sprint h2':['Le Sprint<br>des provinces','Province<br>Sprint'],'#sprint .sprint-heading p':['Associe chaque province à son chef-lieu. Dix manches, trois vies et un nouveau défi à chaque partie.','Match each province with its capital. Ten rounds, three lives and a new challenge every game.'],'.sprint-best span':['MEILLEUR SCORE','BEST SCORE'],'.sprint-best small':['points','points'],'.sprint-play>small':['QUEL EST LE CHEF-LIEU DE…','WHAT IS THE CAPITAL OF…'],
  '#quiz .quiz-intro .eyebrow':['Défi du jour','Daily challenge'],'#quiz .quiz-intro h2':['Prêt à tester tes connaissances ?','Ready to test your knowledge?'],'#quiz .quiz-intro>p':['Dix questions adaptées à ton niveau pour voyager à travers la RDC.','Ten age-appropriate questions for a journey across the DRC.'],'#levelPicker button:nth-child(1) strong':['Explorateur','Explorer'],'#levelPicker button:nth-child(1) small':['7–10 ANS','AGES 7–10'],'#levelPicker button:nth-child(2) strong':['Aventurier','Adventurer'],'#levelPicker button:nth-child(2) small':['11–14 ANS','AGES 11–14'],'#levelPicker button:nth-child(3) strong':['Maître','Master'],'#levelPicker button:nth-child(3) small':['15+ ANS','AGES 15+'],'.score-preview small':['MEILLEUR SCORE','BEST SCORE'],
  '#enseignants .eyebrow':['Espace enseignants','Teacher area'],'#enseignants h2':['Mboka entre<br>en classe.','Bring Mboka<br>to the classroom.'],'#enseignants .teacher-intro>p':['Crée une fiche d’activité prête à imprimer à partir des questions du jeu.','Create a printable activity sheet using questions from the game.'],'.builder-top small':['GÉNÉRATEUR DE FICHE','WORKSHEET GENERATOR'],'.builder-top h3':['Préparer une activité','Prepare an activity'],'#generateWorksheet':['↻ Nouvelle fiche','↻ New worksheet'],'#printWorksheet':['Imprimer la fiche','Print worksheet'],'.teacher-note':['L’impression permet aussi d’enregistrer la fiche au format PDF.','Printing also lets you save the worksheet as a PDF.'],
  '#pilot .eyebrow':['PROGRAMME PILOTE','PILOT PROGRAM'],'#pilot h2':['Aide Mboka<br>à grandir.','Help Mboka<br>grow.'],'#pilot .pilot-intro>p':['Un retour court et anonyme pour améliorer l’exactitude, la difficulté et le plaisir d’apprendre.','Short, anonymous feedback to improve accuracy, difficulty and learning enjoyment.'],'.pilot-privacy':['◈ Aucun nom, courriel ou compte demandé. Les réponses restent sur cet appareil jusqu’à leur exportation.','◈ No name, email or account requested. Responses stay on this device until exported.'],'.pilot-form-head small':['QUESTIONNAIRE · 2 MINUTES','SURVEY · 2 MINUTES'],'.pilot-form-head h3':['Ton expérience','Your experience'],'.pilot-grid label:nth-child(1)>span':['Je réponds comme','I am responding as'],'.pilot-grid label:nth-child(2)>span':['Mboka est facile à utiliser','Mboka is easy to use'],'.pilot-grid label:nth-child(3)>span':['Apprendre avec Mboka est amusant','Learning with Mboka is fun'],'.pilot-grid label:nth-child(4)>span':['J’ai appris quelque chose sur la RDC','I learned something about the DRC'],'.pilot-grid label:nth-child(5)>span':['Mon activité préférée','My favourite activity'],'.pilot-comment>span':['Une suggestion ? (facultatif)','A suggestion? (optional)'],'#pilotForm button[type="submit"]':['Enregistrer le retour','Save feedback'],'#exportFeedback':['Exporter en CSV','Export CSV'],'#clearFeedback':['Effacer','Clear'],
  'footer>p:nth-of-type(1)':['Apprendre. Explorer. Transmettre.','Learn. Explore. Share.'],'#privacyLink':['Confidentialité','Privacy'],
  '#profileTitle':['Kimi','Kimi'],'.profile-cover>span':['MON CARNET D’EXPLORATEUR','MY EXPLORER NOTEBOOK'],'.level-row small':['PROGRESSION GLOBALE','OVERALL PROGRESS'],'.profile-stats>div:nth-child(1) small':['MEILLEUR QUIZ','BEST QUIZ'],'.profile-stats>div:nth-child(2) small':['RECORD SPRINT','SPRINT RECORD'],'.profile-stats>div:nth-child(3) small':['PARCOURS','JOURNEYS'],'.badge-heading small':['MA COLLECTION','MY COLLECTION'],'.badge-heading h3':['Badges à débloquer','Badges to unlock'],'#resetProgress':['Réinitialiser ma progression','Reset my progress']
};
const htmlSelectors=new Set(['.hero h1','#memory h2','#provinces h2','#sprint h2','#enseignants h2','#pilot h2']);
function applyLanguage(lang){
  document.documentElement.lang=lang;localStorage.setItem('mbokaLang',lang);
  Object.entries(uiCopy).forEach(([selector,copy])=>{const el=document.querySelector(selector);if(!el)return;if(htmlSelectors.has(selector))el.innerHTML=copy[lang==='en'?1:0];else el.textContent=copy[lang==='en'?1:0]});
  const search=document.querySelector('#provinceSearch');search.placeholder=lang==='en'?'Search for a province…':'Chercher une province…';
  const comment=document.querySelector('#feedbackComment');if(comment)comment.placeholder=lang==='en'?'What you liked or what should change…':'Ce que tu as aimé ou ce qui devrait changer…';
  document.querySelector('#profileButton').setAttribute('aria-label',lang==='en'?'Open my profile':'Ouvrir mon profil');
  localizeDynamic(lang);
}
let localizationBusy=false;
const languageSelect=document.querySelector('#languageSelect');languageSelect.value=localStorage.getItem('mbokaLang')||'fr';languageSelect.addEventListener('change',e=>{localStorage.setItem('mbokaLang',e.target.value);location.reload()});applyLanguage(languageSelect.value);

function setText(el,value){if(el&&el.textContent!==String(value))el.textContent=value}
function localizeDynamic(lang){
  if(lang!=='en'||localizationBusy)return;localizationBusy=true;const en=window.enContent;
  document.querySelectorAll('[data-journey]').forEach((card,i)=>{setText(card.querySelector('h3'),en.journeys[i].title);setText(card.querySelector('p'),en.journeys[i].text);setText(card.querySelector('small'),`JOURNEY ${String(i+1).padStart(2,'0')}`)});
  const regionNames={Toutes:'All',Ouest:'West',Centre:'Centre',Nord:'North',Est:'East',Sud:'South'};document.querySelectorAll('#regionFilters [data-region]').forEach(b=>setText(b,regionNames[b.dataset.region]));document.querySelectorAll('#provinceList [data-province]').forEach(card=>{const i=provinces.findIndex(p=>p[0]===card.dataset.province);if(i>=0)setText(card.querySelector('.province-region'),en.provinces[i][0])});
  if(typeof selectedMapProvince!=='undefined'&&selectedMapProvince>=0){const p=provinces[selectedMapProvince],d=en.provinces[selectedMapProvince];setText(document.querySelector('#mapZone'),d[0]);setText(document.querySelector('#mapProvince'),p[0]);setText(document.querySelector('#mapDescription'),d[2]);setText(document.querySelector('#mapCapital'),p[1]);setText(document.querySelector('#mapLandmark'),d[1])}
  if(typeof current!=='undefined'&&document.querySelector('#questionView')&&!document.querySelector('#questionView').hidden){const enBank=quizLevel==='adventurer'?en.questions:en.levelQuestions[quizLevel],frBank=levelQuestionBanks[quizLevel],q=enBank[current],topics={PAYS:'COUNTRY',ANIMAUX:'ANIMALS',EAUX:'WATER',PROVINCES:'PROVINCES',LANGUES:'LANGUAGES',MUSIQUE:'MUSIC',NATURE:'NATURE',DRAPEAU:'FLAG',LACS:'LAKES',HYDROGRAPHIE:'HYDROGRAPHY',PATRIMOINE:'HERITAGE',GÉOGRAPHIE:'GEOGRAPHY',BIODIVERSITÉ:'BIODIVERSITY',RELIEF:'LANDFORMS',MINERAIS:'MINERALS',HISTOIRE:'HISTORY',CONSERVATION:'CONSERVATION',CULTURE:'CULTURE',FORÊTS:'FORESTS',VOLCANS:'VOLCANOES'};setText(document.querySelector('#questionNumber'),`QUESTION ${current+1} OF 10`);setText(document.querySelector('#questionTopic'),topics[frBank[current].topic]||frBank[current].topic);setText(document.querySelector('#questionText'),q.q);document.querySelectorAll('#answers .answer').forEach((b,i)=>{const prefix=String.fromCharCode(65+i)+'. ';if(b.textContent!==prefix+q.a[i])b.innerHTML=`<span>${prefix}</span>${q.a[i]}`});if(typeof answered!=='undefined'&&answered){const ok=document.querySelector('#answers .wrong')===null;const box=document.querySelector('#feedback'),key=`${quizLevel}-${current}-${ok}`;if(box.dataset.translation!==key){box.innerHTML=`<strong>${ok?'Well done! +100 points':'Not quite.'}</strong>${q.fact}`;box.dataset.translation=key}setText(document.querySelector('#nextButton'),current===9?'See my result →':'Next question →')}}
  const lesson=document.querySelector('#learningModal');if(lesson&&!lesson.hidden){const title=document.querySelector('#lessonTitle').textContent;const i=journeys.findIndex((j,n)=>j.title===title||en.journeys[n].title===title);if(i>=0){setText(document.querySelector('#lessonTitle'),en.journeys[i].title);setText(document.querySelector('#lessonLead'),en.journeys[i].lead);const facts=document.querySelector('#lessonFacts');if(facts.dataset.translation!==String(i)){facts.innerHTML=en.journeys[i].facts.map((f,n)=>`<div class="lesson-fact"><span>${n+1}</span><div><strong>${f[0]}</strong><p>${f[1]}</p></div></div>`).join('');facts.dataset.translation=String(i)}setText(document.querySelector('#lessonLabel'),'JOURNEY');setText(document.querySelector('#lessonNumber'),`JOURNEY ${String(i+1).padStart(2,'0')}`)}else{const p=provinces.find(x=>x[0]===title);if(p){setText(document.querySelector('#lessonLead'),`${p[1]} is the capital of ${p[0]} province.`);document.querySelector('#lessonFacts').innerHTML=`<div class="lesson-fact"><span>1</span><div><strong>Province</strong><p>${p[0]}</p></div></div><div class="lesson-fact"><span>2</span><div><strong>Capital</strong><p>${p[1]}</p></div></div><div class="lesson-fact"><span>3</span><div><strong>Coming soon</strong><p>The territories, landscapes, languages and cultures of this province will be added to its next notebook.</p></div></div>`;setText(document.querySelector('#lessonLabel'),'PROVINCE CARD');setText(document.querySelector('#lessonNumber'),'ONE OF 26 PROVINCES')}}setText(document.querySelector('#lessonQuiz'),'Take the quiz →')}
  if(lesson&&!lesson.hidden){const title=document.querySelector('#lessonTitle').textContent,pi=provinces.findIndex(p=>p[0]===title);if(pi>=0){const p=provinces[pi],d=en.provinces[pi],facts=document.querySelector('#lessonFacts');setText(document.querySelector('#lessonLead'),`${p[1]} is the capital of ${p[0]} province. ${d[2]}`);if(facts.dataset.translation!=='rich-province'){facts.innerHTML=[['Broad region',d[0]],['Capital',p[1]],['Discover',d[1]]].map((f,n)=>`<div class="lesson-fact"><span>${n+1}</span><div><strong>${f[0]}</strong><p>${f[1]}</p></div></div>`).join('');facts.dataset.translation='rich-province'}setText(document.querySelector('#lessonLabel'),'PROVINCE PROFILE');setText(document.querySelector('#lessonNumber'),`PROVINCE ${String(pi+1).padStart(2,'0')} OF 26`)}}
  document.querySelectorAll('.memory-card').forEach(card=>{const strong=card.querySelector('.memory-front strong'),small=card.querySelector('.memory-front small');if(en.memory[strong?.textContent])setText(strong,en.memory[strong.textContent]);if(en.memory[small?.textContent])setText(small,en.memory[small.textContent])});setText(document.querySelector('#memoryRestart'),'Shuffle and play again');
  [['#memoryMoves','MOVES '],['#memoryPairs','PAIRS '],['#memoryBest','BEST ']].forEach(([selector,label])=>{const el=document.querySelector(selector);if(el?.parentNode.firstChild?.nodeType===3)el.parentNode.firstChild.nodeValue=label});const memoryDone=document.querySelector('#memoryComplete');if(memoryDone&&!memoryDone.hidden){setText(document.querySelector('#memoryTitle'),memoryMoves<=9?'Exceptional memory!':'All six treasures found!');setText(document.querySelector('#memoryMessage'),`Game completed in ${memoryMoves} moves. Your best is ${localStorage.getItem('mbokaMemoryBest')}.`)}
  [['#sprintRound','ROUND '],['#sprintStreak','STREAK '],['#sprintLives','LIVES '],['#sprintScore','SCORE ']].forEach(([selector,label])=>{const el=document.querySelector(selector);if(el?.parentNode.querySelector('small'))setText(el.parentNode.querySelector('small'),label.trim())});
  if(typeof sprintAnswered!=='undefined'&&sprintAnswered){const correct=sprintDeck[sprintIndex][1];if(sprintFeedback.classList.contains('good'))setText(sprintFeedback,`Correct! ${correct} is the capital. Keep your streak going!`);else setText(sprintFeedback,`The correct answer was ${correct}.`);setText(sprintNext,(sprintIndex===9||sprintLives===0)?'See my result →':'Next round →')}
  const sprintResult=document.querySelector('#sprintResult');if(sprintResult&&!sprintResult.hidden){setText(document.querySelector('#sprintResultTitle'),sprintScore>=1200?'Province master!':sprintScore>=700?'Great journey!':'Keep exploring!');setText(document.querySelector('#sprintFinalScore'),`${sprintScore} points`);setText(document.querySelector('#sprintResultText'),`You completed ${sprintIndex+1} rounds. Play again: provinces and answers change every sprint.`);setText(document.querySelector('#sprintRestart'),'New sprint')}
  const quizResult=document.querySelector('#resultView');if(quizResult&&!quizResult.hidden){setText(document.querySelector('#resultTitle'),score>=8?'Remarkable explorer!':score>=5?'Great exploration!':'Your journey begins!');setText(document.querySelector('#resultMessage'),score>=8?'You already know the DRC very well. Keep exploring!':'Every question is a new discovery. Play again to improve your score.');setText(document.querySelector('#restartButton'),'Play again')}
  document.querySelectorAll('#badgeGrid .badge').forEach((badge,i)=>{if(!en.badges[i])return;setText(badge.querySelector('strong'),en.badges[i][0]);setText(badge.querySelector('p'),en.badges[i][1])});
  const rank=document.querySelector('#profileRank');if(rank){const p=Number(document.querySelector('#profilePercent').textContent.replace('%',''))||0;setText(rank,p>=90?'Master of the land':p>=60?'Great explorer':p>=25?'Curious explorer':'New explorer')}
  if(typeof renderWorksheet==='function')renderWorksheet();
  localizationBusy=false;
}
window.refreshLanguage=()=>applyLanguage(languageSelect.value);
let lastDynamicSignature='';
function dynamicSignature(){return[typeof quizLevel==='undefined'?'':quizLevel,typeof current==='undefined'?'':current,typeof answered==='undefined'?'':answered,document.querySelector('#lessonTitle')?.textContent||'',document.querySelector('#learningModal')?.hidden,typeof sprintIndex==='undefined'?'':sprintIndex,typeof sprintAnswered==='undefined'?'':sprintAnswered,document.querySelector('#sprintResult')?.hidden,typeof memoryMatches==='undefined'?'':memoryMatches,document.querySelector('#profileModal')?.hidden].join('|')}
const languageObserver=new MutationObserver(()=>{if(languageSelect.value!=='en'||localizationBusy)return;const signature=dynamicSignature();if(signature===lastDynamicSignature)return;lastDynamicSignature=signature;requestAnimationFrame(()=>localizeDynamic('en'))});languageObserver.observe(document.body,{childList:true,subtree:true});
