const fs=require('fs');
const vm=require('vm');
function assert(condition,message){if(!condition)throw new Error(message)}
const required=['index.html','privacy.html','app.js','i18n.js','content-en.js','math.js','music-game.js','chess-game.js','province-boundaries.js','sw.js','manifest.webmanifest','vercel.json','hardening.css','responsive.css','real-map.css','achievements.css','kingdoms.css','communities.css','food.css','environment.css','resources.css','creativity.css','math.css','music-game.css','chess-game.css','icon.svg','README.md','PRESENTATION.md','CHANGELOG.md'];
required.forEach(file=>assert(fs.existsSync(file),`Missing required file: ${file}`));
const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));
const vercel=JSON.parse(fs.readFileSync('vercel.json','utf8'));
assert(manifest.start_url==='./index.html','Manifest start URL is incorrect');
const globalHeaders=vercel.headers.find(entry=>entry.source==='/(.*)').headers;
const headerNames=new Set(globalHeaders.map(header=>header.key));
['Content-Security-Policy','X-Content-Type-Options','Referrer-Policy','Permissions-Policy','X-Frame-Options','Cross-Origin-Opener-Policy'].forEach(name=>assert(headerNames.has(name),`Missing security header: ${name}`));
const html=fs.readFileSync('index.html','utf8');
assert(!/https?:\/\//.test(html),'index.html contains an external network dependency');
assert(html.includes('privacy.html'),'Privacy link is missing');
const privacy=fs.readFileSync('privacy.html','utf8');
assert(privacy.includes('id="privacy-en"')&&privacy.includes('What Mboka stores')&&privacy.includes('Children and school environments'),'Complete English privacy information is missing');
const readme=fs.readFileSync('README.md','utf8'),presentation=fs.readFileSync('PRESENTATION.md','utf8');
for(const phrase of ['two-team mode','lesson plans','progress reports'])assert(readme.includes(phrase),`README is missing current feature: ${phrase}`);
for(const phrase of ['deux équipes','plan de leçon','rapport individuel de progression','two-team classroom mode','lesson plan','individual progress report'])assert(presentation.includes(phrase),`Presentation is missing current feature: ${phrase}`);
assert(html.includes('id="privacyLink"'),'Privacy link must have a stable translation target');
assert(!fs.readFileSync('i18n.js','utf8').includes("'footer>p:nth-of-type(2)'"),'Localization must not overwrite the privacy-link container');
assert(html.includes('id="pilotForm"'),'Anonymous pilot form is missing');
assert(html.includes('id="mathUnitGrid"')&&html.includes('id="mathLevelPicker"'),'Everyday mathematics interface is missing');
assert(html.includes('id="musicKeyboard"')&&html.includes('id="musicSectionList"'),'Interactive music-learning interface is missing');
assert(html.includes('id="chessBoard"')&&html.includes('id="chessSectionList"'),'Interactive chess-learning interface is missing');
assert(html.includes('id="chessSpeak"'),'Chess spoken-instruction control is missing');
assert(html.includes('class="skip-link"')&&html.includes('class="module-nav"'),'Accessible quick navigation is missing');
assert(html.includes('class="pathway-menu"')&&html.includes('href="#enseignants">Enseignants</a>'),'Teacher and learning-path navigation is missing');
assert(html.includes('href="#musicLab">Musique</a>')&&html.includes('href="#chessLab">Échecs</a>'),'Music and chess navigation links are missing');
assert(html.includes('id="provinceBoundaryLayer"')&&html.includes('geoBoundaries COD ADM1'),'Real 26-province map or attribution is missing');
assert(html.includes('id="worksheetLevel"')&&html.includes('id="worksheetTopic"'),'Teacher worksheet filters are missing');
assert(html.includes('id="printLessonPlan"'),'Printable lesson-plan button is missing');
assert(html.includes('id="printProgress"'),'Printable progress-report button is missing');
assert(html.includes('id="sprintMode"'),'Province Sprint team-mode control is missing');
assert(!/<input[^>]+type=["'](?:email|password)["']/i.test(html),'Pilot must not request email or passwords');
const app=fs.readFileSync('app.js','utf8');
const math=fs.readFileSync('math.js','utf8');
assert(math.includes('const mathUnits=')&&((math.match(/title:\[/g)||[]).length===10),'Everyday mathematics must contain 10 units');
const music=fs.readFileSync('music-game.js','utf8');
assert(music.includes('const musicSections=')&&((music.match(/title:\[/g)||[]).length===4),'Music learning must contain 4 sections');
assert(music.includes('musicIsiOS')&&music.includes('playMusicFile'),'Music learning must include the iOS audio-file fallback');
assert(music.includes('highlightMusicKey(note)'),'Music playback must visually highlight each note');
for(const note of ['C','Cs','D','Ds','E','F','Fs','G','Gs','A','As','B'])assert(fs.existsSync(`music-${note}.wav`),`Missing iOS music note: ${note}`);
const chess=fs.readFileSync('chess-game.js','utf8');
assert(chess.includes('const chessSections=')&&((chess.match(/title:\[/g)||[]).length===7),'Chess learning must contain 7 sections');
assert(chess.includes('mbokaChessProgress')&&chess.includes('saveChessSection'),'Chess learning must save measurable local progress');
assert(chess.includes('class="chess-piece"'),'Chess pieces must have dedicated responsive sizing');
assert(fs.readFileSync('responsive.css','utf8').includes('.chess-square.dark .chess-coord'),'Chess coordinates must remain legible on dark squares');
assert(chess.includes("querySelector('#chessSpeak')")&&chess.includes('speakPhrase'),'Chess instructions must support spoken playback');
assert(chess.includes("control.textContent='🔊'"),'Spoken-text controls must use the speaker symbol');
assert(app.includes("soundEnabled?'🔊':'🔇'"),'Global sound control must use speaker symbols');
assert(app.includes('renderLessonPlan'),'Printable lesson-plan generator is missing');
assert(app.includes('renderProgressReport'),'Printable progress-report generator is missing');
assert(app.includes("sprintMode==='team'"),'Province Sprint team-mode logic is missing');
assert(!/\beval\s*\(|new\s+Function\s*\(/.test(app),'Unsafe dynamic code execution found');
assert((app.match(/name:'/g)||[]).length>=4&&app.includes('achievementProfiles'),'Achievement profiles are incomplete');
assert(app.includes('kingdomProfiles')&&['Kongo','Luba','Lunda','Kuba'].every(name=>app.includes(`name:'${name}'`)),'Traditional kingdom profiles are incomplete');
assert(app.includes('communityProfiles')&&app.includes('renderCommunities'),'Community cultural profiles are incomplete');
assert(app.includes('foodProfiles')&&['Pondu','Fufu','Liboke','Chikwangue','Mikate'].every(name=>app.includes(`name:'${name}'`)),'Food culture profiles are incomplete');
assert(app.includes('environmentProfiles')&&app.includes('renderEnvironment'),'Environment and science profiles are incomplete');
assert(app.includes('resourceProfiles')&&app.includes('supplySteps')&&app.includes('renderResources'),'Natural-resource learning profiles are incomplete');
assert(app.includes('creativityProfiles')&&app.includes('renderCreativity'),'Music, art and creativity profiles are incomplete');
for(const [name,count] of [['provinces',26],['provinceDetails',26],['mapPositions',26]]){const match=app.match(new RegExp(`const ${name} =? ?\\[(.*?)\\];`,'s'));assert(match,`Could not find ${name}`);const actual=name==='mapPositions'?(match[1].match(/\[\d+,\d+\]/g)||[]).length:(match[1].match(/\['/g)||[]).length;assert(actual===count,`${name} has ${actual} entries; expected ${count}`)}
for(const name of ['explorerQuestions','masterQuestions']){const match=app.match(new RegExp(`const ${name}=\\[(.*?)\\];`,'s'));assert(match&&((match[1].match(/\{topic:/g)||[]).length===10),`${name} must contain 10 questions`)}
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('content-en.js','utf8'),sandbox);const en=sandbox.window.enContent;
const mapSandbox={window:{}};vm.runInNewContext(fs.readFileSync('province-boundaries.js','utf8'),mapSandbox);assert(mapSandbox.window.drcProvinceBoundaries.length===26,'Real province boundary map must contain 26 provinces');
assert(en.provinces.length===26,'English province profiles must contain 26 entries');assert(en.questions.length===10&&en.levelQuestions.explorer.length===10&&en.levelQuestions.master.length===10,'English quiz banks must contain 10 questions each');
assert(en.provinceProfiles.length===26&&en.provinceProfiles.every(profile=>profile.length===5),'English cultural province profiles must contain 26 complete entries');
const profileMatch=app.match(/const provinceProfiles = \[(.*?)\];/s);assert(profileMatch&&((profileMatch[1].match(/^  \[/gm)||[]).length===26),'French cultural province profiles must contain 26 entries');
const build=fs.readFileSync('build.js','utf8'),worker=fs.readFileSync('sw.js','utf8');
const buildFiles=[...build.matchAll(/'([^']+)'/g)].map(match=>match[1]).filter(file=>fs.existsSync(file)&&fs.statSync(file).isFile());
for(const file of buildFiles)assert(worker.includes(`./${file}`)||file==='sw.js',`Service worker does not cache build asset: ${file}`);
console.log('Mboka validation passed: security, privacy, content counts, and offline assets.');
